name: Build Container Images
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Build DNS listener image
        run:
          docker build -t gh-dns-listener:${{ github.sha }} --file dusseldorf/dns-listener_Dockerfile ./dusseldorf

      - name: Build HTTP listener image
        run:
          docker build -t gh-http-listener:${{ github.sha }} --file dusseldorf/http-listener_Dockerfile ./dusseldorf
      
      - name: Build API image
        run:
          docker build -t gh-api:${{ github.sha }} --file dusseldorf/api_Dockerfile ./dusseldorf
