name: Build and Push Container Images ACR
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout code
        uses: actions/checkout@main

      - name: Build and push DNS listener image
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az acr build --image gh-dns-listener:${{ github.sha }} --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --file dusseldorf/dns-listener_Dockerfile ./dusseldorf

      - name: Build and push HTTP listener image
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az acr build --image gh-http-listener:${{ github.sha }} --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --file dusseldorf/http-listener_Dockerfile ./dusseldorf

      - name: Build and push API image
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az acr build --image gh-api:${{ github.sha }} --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --file dusseldorf/api_Dockerfile ./dusseldorf
